/** Clean browser fallback for public, robots-permitted staff pages. */
import fs from 'node:fs';import path from 'node:path';import {pathToFileURL}from'node:url';import {gzipSync}from'node:zlib';
import {collectPublicProfileCards,profileCoverage}from'../pilot/browser-profiles.mjs';
import {extractPage,splitPublishedName,validEmail,hash,dedupe,norm}from'./extract.mjs';
import {safeURL,address,robotsPolicy,sameSite,sleep}from'./network.mjs';
import {isAllowedByRobots}from'../crawler/robots.ts';
async function main(){const root=process.argv.find(a=>a.startsWith('--data='))?.slice(7)||'data/full-run-20261001';const workers=3;const playwright=await import(process.env.PLAYWRIGHT_MODULE?pathToFileURL(process.env.PLAYWRIGHT_MODULE).href:'playwright-core');const browser=await playwright.chromium.launch({headless:true,...(process.env.BROWSER_EXECUTABLE?{executablePath:process.env.BROWSER_EXECUTABLE}:{})});fs.mkdirSync(path.join(root,'browser'),{recursive:true});let done=0,total=0;
 async function processSchool(r){const out={schoolId:r.school.externalRegistryId,website:r.website,pages:[],contacts:[],review:[],notes:[],profiles:[],startedAt:new Date().toISOString()};const context=await browser.newContext({serviceWorkers:'block',acceptDownloads:false,userAgent:'seznam-skol/0.2 (+https://github.com/KadlecekTomas/seznam-skol)',viewport:{width:1440,height:1000}});
 const checkedHosts=new Map();await context.route('**/*',async route=>{try{const req=route.request();const u=safeURL(req.url());if(req.method()!=='GET'||['image','font','media'].includes(req.resourceType()))return await route.abort();const own=sameSite(u.href,r.website);const trustedAsset=['cdn.jsdelivr.net','cdnjs.cloudflare.com','ajax.googleapis.com','code.jquery.com'].includes(u.hostname);if((req.isNavigationRequest()&&!own)||(!own&&!trustedAsset))return await route.abort();if(!checkedHosts.has(u.hostname))checkedHosts.set(u.hostname,address(u.hostname));await checkedHosts.get(u.hostname);const p=await robotsPolicy(u.href);if(!isAllowedByRobots(p.text,u.href))return await route.abort();await route.continue();}catch{await route.abort().catch(()=>{});}});
 try{const page=await context.newPage();const targets=[...new Map(r.browserTargets.map(x=>[x.url,x])).values()].sort((a,b)=>((b.profileCards||0)*100+(/sbor|zamestnan|ucitele|vedeni|staff|teachers/i.test(new URL(b.url).pathname)?20:0))-((a.profileCards||0)*100+(/sbor|zamestnan|ucitele|vedeni|staff|teachers/i.test(new URL(a.url).pathname)?20:0))).slice(0,3);for(const t of targets){try{const p=await robotsPolicy(t.url);if(!isAllowedByRobots(p.text,t.url)){out.notes.push('ROBOTS_DISALLOWED:'+t.url);continue;}const res=await page.goto(t.url,{waitUntil:'domcontentloaded',timeout:20000});if(!res||res.status()!==200){out.notes.push('HTTP_'+res?.status()+':'+t.url);continue;}await page.waitForTimeout(1000);
 // Only expand explicit read-only staff accordions; never submit forms or click email buttons.
 const controls=page.locator('details > summary,[aria-expanded="false"]');for(let i=0;i<Math.min(await controls.count(),20);i++){const c=controls.nth(i);const label=norm(await c.innerText().catch(()=>''));if(/pedagog|učitel|zaměstnan|sbor|staff|teachers|1\. stupeň|2\. stupeň|netřídní|asistent|vychovatel/i.test(label)&&await c.isVisible()){await c.click({timeout:1500}).catch(()=>{});await page.waitForTimeout(100);}}
 const html=await page.evaluate(()=>{const root=document.body.cloneNode(true),original=[document.body,...document.body.querySelectorAll('*')],clones=[root,...root.querySelectorAll('*')];for(let i=original.length-1;i>0;i--){const e=original[i];if(['SCRIPT','STYLE','NOSCRIPT','TEMPLATE','IFRAME'].includes(e.tagName)||getComputedStyle(e).display==='none'||getComputedStyle(e).visibility==='hidden')clones[i]?.remove();}return '<html><head><title>'+document.title+'</title></head>'+root.outerHTML+'</html>';});const parsed=extractPage(html,page.url());out.contacts.push(...parsed.contacts.map(c=>({...c,method:'BROWSER_VISIBLE_DOM'})));out.review.push(...parsed.review);out.pages.push({url:page.url(),at:new Date().toISOString(),hash:hash(html),contacts:parsed.contacts.length,profiles:parsed.profileCards});fs.writeFileSync(path.join(root,'browser',hash(t.url)+'.html.gz'),gzipSync(html));
 if(parsed.profileCards){const capture=await page.evaluate(collectPublicProfileCards,{maxCards:300});const coverage=profileCoverage(capture);out.profiles.push({url:t.url,...coverage});fs.writeFileSync(path.join(root,'browser',hash(t.url)+'.profiles.json.gz'),gzipSync(JSON.stringify(capture)));for(const o of capture.observations){if(o.status!=='OPENED'){out.review.push({reason:o.status,url:t.url,name:o.cardName});continue;}const n=splitPublishedName(o.publishedName);if(!n||o.publishedEmails.length!==1||!validEmail(o.publishedEmails[0])){out.review.push({reason:!n?'NAME_NEEDS_REVIEW':o.publishedEmails.length?'MULTIPLE_EMAILS':'NO_PUBLISHED_EMAIL',url:t.url,name:o.publishedName});continue;}out.contacts.push({...n,email:o.publishedEmails[0].toLowerCase(),role:norm(o.text.split('\n').slice(2,4).join(' ')),sourceUrl:t.url,evidenceText:o.text,evidenceHash:hash(o.text),method:'BROWSER_PROFILE_CARD',observedAt:o.observedAt});}if(coverage.status!=='PROFILES_CHECKED')out.notes.push('PROFILE_COVERAGE_PARTIAL:'+t.url);}
 const text=await page.locator('body').innerText();if(/ověřte.*člověk|verify.*human|captcha|access denied/i.test(text))out.notes.push('ACCESS_CHALLENGE:'+t.url);
 }catch(e){out.notes.push((e.name||'BROWSER_ERROR')+':'+t.url);}}
 if(r.browserTargets.length>3)out.notes.push('BROWSER_PAGE_BUDGET:'+r.browserTargets.length);
 const d=dedupe(out.contacts);out.contacts=d.contacts;out.review.push(...d.conflicts);out.finishedAt=new Date().toISOString();return out;
 }finally{await context.close();}}
 const inFlight=new Set();let lastScanCount=0,idle=0;try{while(true){const schoolDir=path.join(root,'schools'),files=fs.readdirSync(schoolDir).filter(f=>f.endsWith('.json'));let pending=files.filter(f=>!fs.existsSync(path.join(root,'browser',f))&&!inFlight.has(f)).map(f=>({f,r:JSON.parse(fs.readFileSync(path.join(schoolDir,f)))})).filter(x=>x.r.parserVersion===2&&x.r.website&&x.r.browserTargets?.length);if(!pending.length){if(process.argv.includes('--once')||files.length>=JSON.parse(fs.readFileSync(path.join(root,'schools.json'))).length)break;if(lastScanCount===files.length)idle++;else idle=0;lastScanCount=files.length;if(idle>120)break;await sleep(3000);continue;}
 const batch=pending.slice(0,workers);await Promise.all(batch.map(async({f,r})=>{inFlight.add(f);let out;try{out=await processSchool(r);}catch(e){out={schoolId:r.school.externalRegistryId,contacts:[],pages:[],profiles:[],notes:[e.message]};}fs.writeFileSync(path.join(root,'browser',f),JSON.stringify(out));inFlight.delete(f);done++;total+=out.contacts.length;console.log(JSON.stringify({browserSchools:done,id:r.school.externalRegistryId,contacts:out.contacts.length,profileCards:out.profiles.reduce((n,p)=>n+p.openedCards,0),notes:out.notes.length,totalBrowserContacts:total}));}));}}finally{await browser.close();}console.log('BROWSER_FINISHED');}
main().catch(e=>{console.error(e);process.exitCode=1;});
