import fs from 'node:fs';import path from 'node:path';import {brotliCompressSync,constants,createGzip}from'node:zlib';import {hash,dedupe,fold,validEmail}from'./extract.mjs';
export function csvCell(value){let s=String(value??'');if(/^[\s]*[=+@-]/.test(s))s="'"+s;return /[;"\r\n]/.test(s)?'"'+s.replace(/"/g,'""')+'"':s;}
const date=s=>new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Prague'}).format(new Date(s));
export function buildResults(schools,scans,browsers,previous={}){const output=[],review=[],schoolRows=[],sources=new Map();for(const s of schools){const r=scans.get(s.externalRegistryId),b=browsers.get(s.externalRegistryId);if(!r){schoolRows.push({school:s,status:'NOT_PROCESSED',contacts:0,website:null});continue;}const d=dedupe([...(r.contacts||[]),...(b?.contacts||[])]);review.push(...(r.review||[]).filter(x=>x.name||x.names||!['EMAIL_WITHOUT_PERSON','GENERAL_MAILBOX'].includes(x.reason)).map(x=>({...x,schoolId:s.externalRegistryId})),...(b?.review||[]).map(x=>({...x,schoolId:s.externalRegistryId})),...d.conflicts.map(x=>({...x,schoolId:s.externalRegistryId})));let count=0;
 for(const c of d.contacts){if(!c.firstName||!c.lastName||!validEmail(c.email)||!r.website||!c.sourceUrl||!c.evidenceText){review.push({schoolId:s.externalRegistryId,email:c.email,reason:'INCOMPLETE_RECORD'});continue;}const text=fold(c.evidenceText),nameWords=fold(c.firstName+' '+c.lastName).split(/\s+/);if(nameWords.some(w=>!text.includes(w))){review.push({schoolId:s.externalRegistryId,email:c.email,reason:'NAME_EVIDENCE_MISMATCH'});continue;}
 const key=s.externalRegistryId+'|'+c.email.toLowerCase(),old=previous[key];if(old&&(fold(old.firstName+' '+old.lastName)!==fold(c.firstName+' '+c.lastName)||old.suppressed)){review.push({schoolId:s.externalRegistryId,email:c.email,reason:old.suppressed?'SUPPRESSED':'IDENTITY_CHANGED'});continue;}
 const collectionDate=old?.collectedAt||date(c.observedAt||r.startedAt);const item={schoolId:s.externalRegistryId,firstName:c.firstName,lastName:c.lastName,email:c.email,schoolName:s.name,schoolAddress:s.addressFull,schoolWebsite:r.website,collectedAt:collectionDate,lastObservedAt:c.observedAt,role:(c.roles||[c.role]).filter(Boolean).join('; '),sourceUrl:c.sourceUrl,sourceUrls:c.sourceUrls||[c.sourceUrl],addressSourceUrl:s.registrySourceUrl,evidenceText:c.evidenceText,evidenceHash:c.evidenceHash,method:c.method,quality:'SOURCE_ASSOCIATED_AUTOMATIC',deliveryVerified:false,marketingPermission:'NOT_ASSESSED'};output.push(item);count++;}
 const notes=[...(r.notes||[]),...(b?.notes||[])];const profiles=b?.profiles||[];const pending=(r.browserTargets||[]).length&&!b;let status=!r.website?'WEB_UNRESOLVED':pending?'BROWSER_PENDING':notes.length||r.remainingRelevantPages?'PARTIAL_COVERAGE':profiles.length&&profiles.every(p=>p.status==='PROFILES_CHECKED')?'PROFILE_DIRECTORY_CHECKED':count?'SOURCES_SCANNED_COMPLETENESS_UNCONFIRMED':'NO_PERSONAL_CONTACTS';
 const namedCards=profiles.reduce((n,p)=>n+p.expectedCards,0),openedCards=profiles.reduce((n,p)=>n+p.openedCards,0);schoolRows.push({school:s,status,contacts:count,website:r.website||null,websiteSource:r.websiteSource||'',pages:(r.pages||[]).length,browserPages:b?.pages?.length||0,profileCards:namedCards,openedCards,remainingPages:r.remainingRelevantPages||0,browserTargets:(r.browserTargets||[]).length,notes,errors:r.errors||[],profiles,allEmployeesKnown:false});}
 output.sort((a,b)=>a.schoolName.localeCompare(b.schoolName,'cs')||a.lastName.localeCompare(b.lastName,'cs')||a.firstName.localeCompare(b.firstName,'cs'));
 const acceptedKeys=new Set(output.map(c=>c.schoolId+'|'+c.email));const unresolvedReview=review.filter(r=>!r.email||!acceptedKeys.has(r.schoolId+'|'+r.email)||/CONFLICT|CHANGED|SHARED|SUPPRESS/.test(r.reason||''));const uniqueReview=[...new Map(unresolvedReview.map(r=>[r.schoolId+'|'+(r.email||r.name||'')+'|'+r.reason+'|'+(r.url||''),r])).values()];
 return {contacts:output,schools:schoolRows,review:uniqueReview,summary:{registrySchools:schools.length,processedSchools:scans.size,schoolsWithWeb:schoolRows.filter(r=>r.website).length,schoolsWithContacts:schoolRows.filter(r=>r.contacts).length,contactRows:output.length,uniqueEmails:new Set(output.map(c=>c.email)).size,uniquePeopleInSchools:new Set(output.map(c=>c.schoolId+'|'+fold(c.firstName+' '+c.lastName))).size,reviewItems:uniqueReview.length,staticPages:schoolRows.reduce((n,r)=>n+(r.pages||0),0),browserPages:schoolRows.reduce((n,r)=>n+(r.browserPages||0),0),profileCards:schoolRows.reduce((n,r)=>n+(r.profileCards||0),0),openedProfileCards:schoolRows.reduce((n,r)=>n+(r.openedCards||0),0),statuses:schoolRows.reduce((o,r)=>(o[r.status]=(o[r.status]||0)+1,o),{})}};}
function readMap(dir){return new Map(fs.readdirSync(dir).filter(f=>/^[0-9]+\.json$/.test(f)).map(f=>[f.slice(0,-5),JSON.parse(fs.readFileSync(path.join(dir,f)))]));}
if(process.argv[1]?.endsWith('/export.mjs')){const root=process.argv.find(a=>a.startsWith('--data='))?.slice(7)||'data/full-run-20261001';const output=process.argv.find(a=>a.startsWith('--output='))?.slice(9)||'exports/prague-full-20261001';const prev=process.argv.find(a=>a.startsWith('--previous='))?.slice(11);const schools=JSON.parse(fs.readFileSync(path.join(root,'schools.json')));const result=buildResults(schools,readMap(path.join(root,'schools')),readMap(path.join(root,'browser')),prev?JSON.parse(fs.readFileSync(prev)):{});fs.mkdirSync(output,{recursive:true});fs.writeFileSync(path.join(output,'result.json'),JSON.stringify(result));fs.writeFileSync(path.join(output,'summary.json'),JSON.stringify(result.summary,null,2));const cols=['firstName','lastName','email','schoolName','schoolAddress','schoolWebsite','collectedAt'];const rows=[['Jméno','Příjmení','E-mail','Škola','Adresa školy','Web','Datum sebrání'],...result.contacts.map(c=>cols.map(k=>c[k]))];fs.writeFileSync(path.join(output,'kontakty.csv'),'\ufeff'+rows.map(r=>r.map(csvCell).join(';')).join('\r\n')+'\r\n');fs.writeFileSync(path.join(output,'ledger.json'),JSON.stringify(Object.fromEntries(result.contacts.map(c=>[c.schoolId+'|'+c.email,c]))));console.log(JSON.stringify(result.summary,null,2));}
