import {load} from 'cheerio';
import {createHash} from 'node:crypto';
export const fold=s=>(s||'').normalize('NFD').replace(/\p{Diacritic}/gu,'').toLowerCase();
export const norm=s=>(s||'').replace(/\s+/g,' ').trim();
export const hash=s=>createHash('sha256').update(s).digest('hex');
const givenNames=new Set(fold(`Adam Adrian Adrián Alena Alex Alexandra Alexandr Alexej Alice Alla Alois Alžběta Amálie Andrea Andrej Aneta Anežka Anna Antonín Barbora Beáta Běla Bohdan Bohumil Bohumila Bohuslav Bohuslava Božena Bronislav Dagmar Dana Daniel Daniela Darina David Denisa Denis Diana Dita Dominik Dominika Dorota Dušan Edita Eduard Eliška Elena Eleonora Emil Emílie Emma Erik Erika Ester Eva Evžen Filip František Františka Gabriela Hana Helena Hynek Ilona Inna Irena Irina Iva Ivan Ivana Iveta Jakub Jan Jana Jaromír Jaromíra Jaroslav Jaroslava Jarmila Jitka Jindřich Jindřiška Jiří Jiřina Johana Jolana Josef Josefa Jozef Julie Julius Justýna Kamila Karel Karla Karolína Katarína Kateřina Klára Kristina Kristýna Květa Květoslava Ladislav Ladislava Laura Lea Lenka Libor Libuše Libuška Linda Lucie Luděk Ludmila Lukáš Magdaléna Magdalena Marcela Marek Margita Marie Mariana Marika Markéta Marta Martin Martina Matěj Matyáš Michael Michaela Michal Milan Milada Milena Miloš Miloslav Miloslava Miroslav Miroslava Monika Naďa Naděžda Natálie Natalie Natalia Nataliia Nataliya Nikola Nikol Nina Olga Oldřich Oldřiška Ondřej Oto Otakar Otto Pavla Pavel Pavlína Patrik Petra Petr Radek Radim Radka Radana Radmila Radoslav Regina Renata René Richard Rita Robert Roman Romana Rostislav Růžena Sabina Sandra Sára Silvia Silvie Simona Stanislav Stanislava Sylva Sylvie Šárka Šimon Štěpán Štěpánka Taťána Tatiana Tereza Tomáš Valentina Václav Vanda Vendula Vendulka Veronika Věra Viktor Viktorie Vít Vladimír Vladimíra Vladislav Vlasta Vlastimil Vlastimila Vojtěch Zbyněk Zdeněk Zdeňka Zdenka Zina Zuzana Žaneta Žofie Geraldine Nela Nicol Nicole Ines Agáta Agata Adéla Adela Anička Berenika Bára Blanka Blažena Bohumír Čestmír Dalibor Dominika Ellen Ema Evelyn Gita Ingrid Ivona Jasmína Joachim Jonáš Kamil Karolina Lada Leo Leona Liana Lili Liliana Lýdie Malvína Manuel Markus Miluše Nadja Nataša Nika Nikita Oleg Oliver Ornella Patricia Patricie Pavlina Radovan Robin Rolanda Samuel Slávka Svatava Svatoslav Tamara Tadeáš Theodor Vasil Verena Vincent Vlasta Wolfgang Yveta Yvona Zdislava Zlatka Natali Vadym Oleksandr Oleksandra Olena Olha Oksana Svitlana Tetiana Yuliia Viktoriia Nina Iryna Zlata John James David Peter Paul Mary Jane Sarah Thomas Mark Elizabeth Michelle Christopher Andrew William Robert Michael Anne Rachel Matthew Sean Brian Kevin Catherine Caroline Jennifer Jonathan Charles Claire Stephen Steven Vanessa Nicholas Tom Robert Patrick Janis`).split(/\s+/));
const generic=new Set(['info','skola','school','office','sekretariat','sekretariát','kancelar','kancelář','recepce','kontakt','mail','email','podatelna','admin','webmaster','noreply','no-reply','support']);
export function validEmail(email){if(typeof email!=='string'||email.length>254||/\s|[<>"',;:]/.test(email)||/[^\x21-\x7e]/.test(email))return false;const parts=email.split('@');if(parts.length!==2)return false;const [a,d]=parts;if(!a||a.length>64||a.startsWith('.')||a.endsWith('.')||a.includes('..')||!d.includes('.'))return false;return d.split('.').every(p=>/^[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$/i.test(p));}
export function decodePublished(text){return (text||'').replace(/\s*(?:\[\s*(?:at|zavin[aá]č)\s*\]|\(\s*(?:at|zavin[aá]č)\s*\))\s*/gi,'@').replace(/\s*(?:\[\s*(?:dot|tečka)\s*\]|\(\s*(?:dot|tečka)\s*\))\s*/gi,'.');}
export function emailsIn(text){return [...new Set((decodePublished(text).match(/[A-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi)||[]).map(s=>s.replace(/^[.]+|[.]+$/g,'').toLowerCase()).filter(validEmail))];}
function cleanName(s){return norm(s)
 .replace(/^(?:(?:prof|doc|Mgr|MgA|Ing|BcA|Bc|PhDr|RNDr|JUDr|PaedDr|ThDr|MUDr|MVDr|DiS|Dis|M\.A|Ph\.D)(?:\.\s*|\s+))+/i,'')
 .replace(/(?:,?\s+(?:Ing\.?|Mgr\.?|Bc\.?|PhDr\.?|RNDr\.?|JUDr\.?|MBA|Ph\.?D\.?|CSc\.?|DiS\.?|MSc\.?|LLM|Dr\.?|ak\.?\s*mal\.?|ml\.?|st\.?))+$|\s*\([^)]*\)\s*$/gi,'').trim();}
export function splitPublishedName(value){let s=cleanName(value);s=s.replace(/\s+/g,' ');const words=s.split(' ');if(words.length<2||words.length>5||words.some(w=>!/^\p{L}[\p{L}\p{M}'’.-]*$/u.test(w)||w.length<2))return null;let first=[],last=[];if(givenNames.has(fold(words[0]))){let i=0;while(i<words.length-1&&givenNames.has(fold(words[i])))first.push(words[i++]);last=words.slice(i);}else if(givenNames.has(fold(words.at(-1)))&&words.length<=3){first=[words.at(-1)];last=words.slice(0,-1);}else return null;if(!first.length||!last.length||last.some(w=>!/^\p{Lu}/u.test(w))||last.some(w=>['skola','ulice','trida','kontakt','classroom','online','praha'].includes(fold(w))))return null;return {firstName:first.join(' '),lastName:last.join(' '),publishedName:norm(value)};}
export function namesIn(text){const results=new Map();const lines=(text||'').split(/[\n\r;|]+/);
 for(const line of lines){const whole=splitPublishedName(line.trim());if(whole){results.set(fold(whole.firstName+'|'+whole.lastName),whole);continue;}
 const rx=/(?<![\p{L}])(?:\p{Lu}[\p{L}'’-]+\s+){1,3}\p{Lu}[\p{L}'’-]+/gu;
 for(const m of line.matchAll(rx)){let p=splitPublishedName(m[0]);if(p)results.set(fold(p.firstName+'|'+p.lastName),p);}
 }return [...results.values()];}
function readable($,el){return $(el).find('*').addBack().contents().filter((_,n)=>n.type==='text').map((_,n)=>n.data).get().join('\n').replace(/[ \t]+/g,' ').replace(/\n\s*\n/g,'\n').trim();}
const roleRX=/(?:ředitel(?:ka)?|zástup(?:ce|kyně)|třídní učitel(?:ka)?|učitel(?:ka)?|vychovatel(?:ka)?|asistent(?:ka)? pedagoga|psycholog(?:ka|žka)?|speciální pedagog|sociální pedagog|koordinátor(?:ka)?|metodik(?:čka)?|ekonom(?:ka)?|hospodář(?:ka)?|vedoucí[^\n]{0,45}|sekretář(?:ka)?)/gi;
export function relevance(url,label=''){let u;try{u=new URL(url);}catch{return -100;}const s=fold(decodeURIComponent(u.pathname)+' '+label);let n=0;for(const [rx,score] of [[/kontakt|contact/,14],[/pedagog|staff|zamestnan|ucitel|teachers|sbor/,20],[/vedeni|leadership|reditel|pracovnic/,14],[/o.skole|about/,5],[/druzina|jidelna|poradensk/,5]])if(rx.test(s))n+=score;if(/aktualit|novink|archiv|foto|galerie|soutez|kalendar|202[0-5]/.test(s))n-=14;if(/\.(pdf|docx?|xlsx?|png|jpe?g|zip|mp4)(?:$)/.test(u.pathname))n=-50;return n;}
export function normalizedURL(href,base){try{const u=new URL(href,base);if(!['http:','https:'].includes(u.protocol)||u.username||u.password)return null;u.hash='';for(const k of [...u.searchParams.keys()])if(/^utm_|fbclid|gclid/.test(k))u.searchParams.delete(k);return u.href;}catch{return null;}}
export function extractPage(html,url){const $=load(html);$('script,style,noscript,template,iframe,[hidden],[aria-hidden="true"]').remove();$('[style]').each((_,el)=>{if(/display\s*:\s*none|visibility\s*:\s*hidden/i.test($(el).attr('style')||''))$(el).remove();});const contacts=[],review=[],seen=new Set();const plain=readable($,$('body'));
 const links=[];$('a[href]').each((_,el)=>{const href=$(el).attr('href'),u=normalizedURL(href,url);if(u)links.push({url:u,label:norm($(el).text()),score:relevance(u,$(el).text())});});
 const title=norm($('title').text()),h1=norm($('h1').first().text());
 function accept(el,email,kind){if(!validEmail(email))return;let current=$(el), evidence='',people=[];for(let level=0;level<8&&current.length;level++,current=current.parent()){
  if(['html','body','footer','nav'].includes(current[0]?.tagName))break;const t=readable($,current);if(t.length>950)break;const blockMails=[...new Set([...emailsIn(t),...current.find('a[href]').map((_,a)=>{let h=$(a).attr('href')||'';try{h=decodeURIComponent(h);}catch{}return /^mailto:/i.test(h)?emailsIn(h):[];}).get().flat()])];if(blockMails.some(x=>x!==email)){evidence=t;people=[];break;}const heading=current.find('h2,h3,h4,h5,[itemprop="name"]').map((_,e)=>norm($(e).text())).get().map(splitPublishedName).filter(Boolean);const rowNames=current.is('tr')?current.find('td,th').map((_,e)=>norm($(e).text())).get().map(splitPublishedName).filter(Boolean):[];const names=[...new Map([...heading,...rowNames,...namesIn(t)].map(p=>[fold(p.firstName+'|'+p.lastName),p])).values()];if(names.length){evidence=t;people=names;break;}if(current.is('tr,li,article')||current.find('h2,h3,h4,h5,[itemprop="name"]').length){evidence=t;people=[];break;}}
  if(!evidence){review.push({email,reason:'EMAIL_WITHOUT_PERSON',url});return;}const key=email+'|'+hash(evidence);if(seen.has(key))return;seen.add(key);
  const e=emailsIn(evidence);const linkEmails=$(el).is('a')?emailsIn(decodeURIComponent($(el).attr('href')?.replace(/^mailto:/i,'').split('?')[0]||'')):[];const visibleEmails=emailsIn($(el).text());
  if(visibleEmails.length&&linkEmails.length&&visibleEmails[0]!==linkEmails[0]){review.push({email,reason:'LINK_TEXT_CONFLICT',url,evidence});return;}
  if(people.length!==1||e.some(x=>x!==email)){review.push({email,reason:'AMBIGUOUS_BLOCK',url,evidence});return;}
  if(/Primirest|sídlo společnosti|webdesign|tvorba webových/i.test(evidence)){review.push({email,reason:'EXTERNAL_SERVICE_CONTACT',url,evidence});return;}if(generic.has(email.split('@')[0])){review.push({email,reason:'GENERAL_MAILBOX',url,evidence});return;}
  const person=people[0];contacts.push({...person,email,role:[...new Set(evidence.match(roleRX)||[])].join('; '),sourceUrl:url,evidenceText:evidence,evidenceHash:hash(evidence),method:kind,observedAt:new Date().toISOString()});
 }
 $('a[href]').each((_,el)=>{const href=$(el).attr('href')||'';if(!/^mailto:/i.test(href))return;let s=href.replace(/^mailto:/i,'').split('?')[0];try{s=decodeURIComponent(s);}catch{}for(const email of emailsIn(s))accept(el,email,'STATIC_MAILTO');});
 $('body').find('*').contents().each((_,node)=>{if(node.type!=='text'||!node.parent)return;for(const e of emailsIn(node.data))accept(node.parent,e,'STATIC_TEXT');});
 const profileCards=$('button,[role="button"]').filter((_,el)=>/zobrazit profil|view profile|detail pracovníka/i.test($(el).text())).length;
 const accordions=$('details:not([open]),[aria-expanded="false"]').filter((_,el)=>/učitel|pedagog|vedení|zaměstn|asistent|vychovatel|1\. stupeň|2\. stupeň|kontakt|sbor|staff/i.test($(el).text())).length;
 const named=namesIn(plain);const distinctEmails=emailsIn(plain);const interactive=profileCards>0||accordions>0;
 const jsShell=plain.length<500&&/<script/.test(html);const pagination=links.some(x=>/další|následující|next|[»›]/i.test(x.label))||$('a[rel="next"]').length>0;
 return {contacts,review,links,title,h1,text:plain,profileCards,accordions,interactive,jsShell,pagination,names:named,visibleEmails:distinctEmails,soft404:/404|stránk[au].*(nenalez|nepodařilo)|page not found/i.test(title+' '+h1)};
}
export function identitySignals(page,school){const text=fold(page.text), tokens=new Set(text.split(/[^a-z0-9]+/));const sig=[];for(const [key,value] of [['ico',school.ico],['redIzo',school.redIzo]])if(value&&tokens.has(value))sig.push(key);if(school.registryEmails.some(e=>page.visibleEmails.includes(e)))sig.push('registryEmail');let street=fold(school.addressStreet||'').replace(/\s+\d.*$/,'');if(street.length>4&&text.includes(street))sig.push('street');const names=fold(school.name).split(/[^a-z]+/).filter(t=>t.length>3&&!['zakladni','skola','stredni','gymnazium','praha','materska','prispevkova','organizace','odborna','vyssi','skol','soukroma'].includes(t));if(names.filter(t=>tokens.has(t)).length>=Math.min(2,names.length)&&names.length)sig.push('name');return sig;}
export function identityOK(signals){return signals.includes('ico')||signals.includes('redIzo')||(signals.includes('registryEmail')&&(signals.includes('name')||signals.includes('street')))||(signals.includes('name')&&signals.includes('street'));}
export function dedupe(contacts){const groups=new Map(),out=[],conflicts=[];for(const c of contacts){const e=c.email.toLowerCase();const list=groups.get(e)||[];list.push(c);groups.set(e,list);}for(const [e,rows]of groups){const names=new Set(rows.map(c=>fold(c.firstName+'|'+c.lastName)));if(names.size>1){conflicts.push({email:e,reason:'SHARED_OR_CONFLICTING_PERSON',names:rows.map(c=>c.publishedName),url:rows[0].sourceUrl});continue;}out.push({...rows[0],sourceUrls:[...new Set(rows.map(c=>c.sourceUrl))],roles:[...new Set(rows.map(c=>c.role).filter(Boolean))]});}return {contacts:out,conflicts};}
