/** Deterministic offline repair from captured public pages, without another website request. */
import fs from 'node:fs';import path from 'node:path';import {gunzipSync}from'node:zlib';
import {extractPage,splitPublishedName,dedupe,fold,hash,validEmail}from'./extract.mjs';
const root=process.argv.find(a=>a.startsWith('--data='))?.slice(7)||'data/full-run-20261001';const index=new Map();
for(const f of fs.readdirSync(path.join(root,'http-cache'))){if(!f.endsWith('.gz'))continue;try{const r=JSON.parse(gunzipSync(fs.readFileSync(path.join(root,'http-cache',f))));if(r.status===200&&r.url)index.set(r.url,{file:f,at:r.at});}catch{}}
let schools=0,browserSchools=0,unavailable=0,priorCount=0,newCount=0;
for(const file of fs.readdirSync(path.join(root,'schools')).filter(f=>f.endsWith('.json'))){const full=path.join(root,'schools',file),r=JSON.parse(fs.readFileSync(full));if(!r.website)continue;priorCount+=r.contacts.length;const contacts=[],review=[];for(const p of r.pages){const ref=index.get(p.url);if(!ref){unavailable++;r.notes.push('SOURCE_CAPTURE_MISSING:'+p.url);continue;}const response=JSON.parse(gunzipSync(fs.readFileSync(path.join(root,'http-cache',ref.file))));const e=extractPage(response.text,p.url);p.contacts=e.contacts.length;for(const c of e.contacts)if(!fold(r.school.name).includes(fold(c.firstName+' '+c.lastName)))contacts.push({...c,observedAt:response.at});review.push(...e.review);}
 const d=dedupe(contacts);r.contacts=d.contacts;r.review=[...review,...d.conflicts];r.parserVersion=3;r.reparsedAt=new Date().toISOString();fs.writeFileSync(full,JSON.stringify(r));schools++;newCount+=r.contacts.length;
 const bf=path.join(root,'browser',file);if(!fs.existsSync(bf))continue;const b=JSON.parse(fs.readFileSync(bf)),bc=[],br=[];for(const p of b.pages||[]){const hp=path.join(root,'browser',hash(p.url)+'.html.gz');if(!fs.existsSync(hp)){b.notes.push('VISIBLE_CAPTURE_MISSING:'+p.url);continue;}const e=extractPage(gunzipSync(fs.readFileSync(hp)).toString(),p.url);bc.push(...e.contacts.map(c=>({...c,method:'BROWSER_VISIBLE_DOM',observedAt:p.at})));br.push(...e.review);}
 for(const p of b.profiles||[]){const pf=path.join(root,'browser',hash(p.url)+'.profiles.json.gz');if(!fs.existsSync(pf))continue;const cap=JSON.parse(gunzipSync(fs.readFileSync(pf)));for(const o of cap.observations){const name=splitPublishedName(o.publishedName);if(o.status!=='OPENED'||!name||o.publishedEmails.length!==1||!validEmail(o.publishedEmails[0])){br.push({name:o.publishedName,reason:!o.publishedEmails?.length?'NO_PUBLISHED_EMAIL':'PROFILE_NAME_REVIEW',url:p.url});continue;}bc.push({...name,email:o.publishedEmails[0].toLowerCase(),role:(o.text.split('\n')[2]||''),sourceUrl:p.url,evidenceText:o.text,evidenceHash:hash(o.text),method:'BROWSER_PROFILE_CARD',observedAt:o.observedAt});}}
 const bd=dedupe(bc);b.contacts=bd.contacts;b.review=[...br,...bd.conflicts];b.parserVersion=3;fs.writeFileSync(bf,JSON.stringify(b));browserSchools++;
}
console.log(JSON.stringify({schools,browserSchools,unavailableCaptures:unavailable,oldStaticCount:priorCount,newStaticCount:newCount},null,2));
