/** Resumable Prague registry -> official sites -> explicit staff candidates. No mail is sent. */
import fs from 'node:fs';import path from 'node:path';import {gzipSync,gunzipSync}from'node:zlib';import {load}from'cheerio';
import {fetchPublic,robotsPolicy,sameSite,sleep} from './network.mjs';
import {extractPage,identitySignals,identityOK,normalizedURL,relevance,fold,hash,dedupe} from './extract.mjs';
const freemail=new Set('gmail.com googlemail.com seznam.cz email.cz post.cz centrum.cz atlas.cz volny.cz outlook.com hotmail.com live.com icloud.com me.com yahoo.com yahoo.co.uk tiscali.cz quick.cz'.split(' '));
export function websiteCandidates(school){const a=[];if(school.website)a.push(school.website);for(const e of school.registryEmails||[]){const h=e.split('@')[1]?.toLowerCase();if(h&&!freemail.has(h)&&/^[a-z0-9.-]+\.[a-z]{2,}$/.test(h)){a.push('https://'+h);if(!h.startsWith('www.'))a.push('https://www.'+h);}}return [...new Set(a)].slice(0,4);}
function distinctLinks(links,base){const m=new Map();for(const l of links){if(!sameSite(l.url,base))continue;let u=new URL(l.url);if(/\/(?:api|wp-admin|wp-json|admin|login|prihlaseni|intranet|__cms|studio)\b/i.test(u.pathname))continue;if(l.score<4)continue;let key=u.href.replace(/\/$/,'');if(!m.has(key)||m.get(key).score<l.score)m.set(key,l);}return [...m.values()].sort((a,b)=>b.score-a.score);}
export async function csiWebsite(school){if(!school.redIzo)return null;const url='https://portal.csicr.cz/School/'+school.redIzo;try{const r=await fetchPublic(url);if(r.status!==200)return null;const $=load(r.text);const text=$('body').text();if(!text.includes(school.redIzo)||/Tento záznam školy není platný/.test(text))return null;let found=null;$('tr').each((_,el)=>{let t=$(el).text().replace(/\s+/g,' ');if(t.includes('Web:')&&t.length<2500&&!found){$(el).find('a[href]').each((_,a)=>{const u=normalizedURL($(a).attr('href'),url);if(u&&!sameSite(u,url)&&!found)found=u;});}});return found?{url:found,source:url}:null;}catch{return null;}}
export async function scanSchool(school,{pageBudget=22}={}){
 const startedAt=new Date().toISOString(),notes=[],errors=[],pages=[],raw=[],reviews=[],seen=new Set(),seenFinal=new Set();let accepted=null,identity=[],officialSource=null,firstPage=null,firstResponse=null;const cache=new Map();
 async function get(url,same=null){if(cache.has(url))return cache.get(url);const captureDir=process.env.CAPTURE_DIR;const f=captureDir?path.join(captureDir,hash(url)+'.json.gz'):null;if(f&&fs.existsSync(f)){const r=JSON.parse(gunzipSync(fs.readFileSync(f)));cache.set(url,r);return r;}const r=await fetchPublic(url,{sameSiteAs:same});cache.set(url,r);if(f&&r.status===200){fs.mkdirSync(captureDir,{recursive:true});const safe={...r,headers:{'content-type':r.headers['content-type']||''}};fs.writeFileSync(f,gzipSync(JSON.stringify(safe)));}return r;}
 const cands=websiteCandidates(school);
 for(let round=0;round<2&&!accepted;round++){
  let candidates=cands;if(round===1){const c=await csiWebsite(school);if(!c)break;candidates=[c.url];officialSource=c.source;}
  for(const url of candidates){try{const r=await get(url);if(r.status!==200||!/html|xhtml/i.test(r.headers['content-type']||'')){errors.push({url,code:'HOME_HTTP_'+r.status});continue;}const p=extractPage(r.text,r.url);if(p.soft404){errors.push({url,code:'SOFT_404'});continue;}let sig=identitySignals(p,school);if(!identityOK(sig)&&!officialSource){for(const l of distinctLinks(p.links,r.url).slice(0,3)){try{const sub=await get(l.url,r.url);if(sub.status===200){sig=[...new Set([...sig,...identitySignals(extractPage(sub.text,sub.url),school)])];if(identityOK(sig))break;}}catch{}}}
    if(identityOK(sig)||officialSource){accepted=r.url;firstPage=p;firstResponse=r;identity=sig;if(officialSource)identity.push('CSI_EXPLICIT_WEB');break;}
    errors.push({url,code:'IDENTITY_NOT_CONFIRMED',signals:sig});
   }catch(e){errors.push({url,code:e.code||e.message});}}
 }
 if(!accepted)return {school,startedAt,finishedAt:new Date().toISOString(),status:'WEBSITE_UNRESOLVED',website:null,pages,contacts:[],review:[],errors,notes:['Web nebyl bezpečně a jednoznačně potvrzen.'],browserTargets:[]};
 const queue=[{url:accepted,score:100,label:'homepage'}],queued=new Set([accepted.replace(/\/$/,'')]),browserTargets=[];let sitemapCount=0;
 const rp=await robotsPolicy(accepted);const maps=[...new Set([...rp.sitemaps,new URL('/sitemap.xml',accepted).href])].filter(u=>sameSite(u,accepted));
 const mapQueue=maps.slice(0,2);while(mapQueue.length&&sitemapCount<4){const u=mapQueue.shift();sitemapCount++;try{const r=await get(u,accepted);if(r.status!==200)continue;const $=load(r.text,{xmlMode:true});if($('sitemapindex').length){for(const m of $('sitemap>loc').map((_,e)=>$(e).text()).get().slice(0,3))if(sameSite(m,accepted))mapQueue.push(m);}else for(const loc of $('url>loc').map((_,e)=>$(e).text()).get()){const url=normalizedURL(loc,accepted);if(url&&sameSite(url,accepted)&&relevance(url)>=4){const k=url.replace(/\/$/,'');if(!queued.has(k)){queued.add(k);queue.push({url,score:relevance(url),label:'sitemap'});}}}}catch(e){errors.push({url:u,code:e.code||e.message});}}
 function enqueue(links){for(const l of distinctLinks(links,accepted)){const k=l.url.replace(/\/$/,'');if(!queued.has(k)){queued.add(k);queue.push(l);}}queue.sort((a,b)=>b.score-a.score);}
 while(queue.length&&pages.length<pageBudget){const l=queue.shift(),key=l.url.replace(/\/$/,'');if(seen.has(key))continue;seen.add(key);try{const r=await get(l.url,accepted);if(r.status!==200){errors.push({url:l.url,code:'HTTP_'+r.status});continue;}if(!/html|xhtml/i.test(r.headers['content-type']||''))continue;const fk=r.url.replace(/\/$/,'');if(seenFinal.has(fk))continue;seenFinal.add(fk);const p=l.url===accepted?firstPage:extractPage(r.text,r.url);if(p.soft404){errors.push({url:l.url,code:'SOFT_404'});continue;}
 const isStaff=/pedagog|staff|zamestnan|ucitel|teachers|sbor|vedeni/.test(fold(r.url+' '+p.title));const uniqueNames=[...new Set(p.names.map(x=>fold(x.firstName+'|'+x.lastName)))];
 const page={url:r.url,observedAt:r.at,hash:hash(r.text),emails:p.visibleEmails.length,contacts:p.contacts.length,names:uniqueNames.length,profileCards:p.profileCards,accordions:p.accordions,pagination:p.pagination,score:l.score};pages.push(page);
 for(const c of p.contacts)if(!fold(school.name).includes(fold(c.firstName+' '+c.lastName)))raw.push({...c,observedAt:r.at});
 reviews.push(...p.review);
 if(p.interactive||p.jsShell||(isStaff&&uniqueNames.length>p.contacts.length+2)){browserTargets.push({url:r.url,reason:p.interactive?'INTERACTIVE_PROFILES':p.jsShell?'JAVASCRIPT_PAGE':'STAFF_COVERAGE_GAP',names:uniqueNames.length,profileCards:p.profileCards});}
 if(p.pagination)notes.push('PAGINATION_DETECTED:'+r.url);
 enqueue(p.links);
 }catch(e){errors.push({url:l.url,code:e.code||e.message});}}
 if(queue.length)notes.push('PAGE_BUDGET_EXHAUSTED:'+queue.length);
 const result=dedupe(raw);return {parserVersion:2,school,startedAt,finishedAt:new Date().toISOString(),status:browserTargets.length?'BROWSER_REVIEW_REQUIRED':result.contacts.length?'STATIC_SOURCE_SCAN':'NO_PERSONAL_CONTACTS_FOUND',website:accepted,websiteSource:officialSource||'REGISTRY_EMAIL_DOMAIN_AND_IDENTITY',identity,pages,contacts:result.contacts,review:[...reviews,...result.conflicts],errors,notes:[...new Set(notes)],remainingRelevantPages:queue.length,browserTargets,allEmployeesKnown:false,deliveryVerified:false};
}
async function main(){const root=process.argv.find(x=>x.startsWith('--data='))?.slice(7)||'data/full-run-20261001';const concurrency=Number(process.argv.find(x=>x.startsWith('--workers='))?.slice(10)||8);const max=Number(process.argv.find(x=>x.startsWith('--limit='))?.slice(8)||99999);if(!Number.isInteger(concurrency)||concurrency<1||concurrency>12)throw Error('Invalid concurrency');const schools=JSON.parse(fs.readFileSync(path.join(root,'schools.json'))).slice(0,max);fs.mkdirSync(path.join(root,'schools'),{recursive:true});let at=0,done=0,totalContacts=0;
 await Promise.all(Array.from({length:concurrency},async()=>{while(at<schools.length){const s=schools[at++],file=path.join(root,'schools',s.externalRegistryId+'.json');if(fs.existsSync(file)){done++;continue;}let r;try{r=await scanSchool(s);}catch(e){r={school:s,status:'FAILED',error:e.message,contacts:[],pages:[],browserTargets:[]};}fs.writeFileSync(file+'.tmp',JSON.stringify(r));fs.renameSync(file+'.tmp',file);done++;totalContacts+=r.contacts.length;console.log(JSON.stringify({done,total:schools.length,id:s.externalRegistryId,status:r.status,contacts:r.contacts.length,pages:r.pages.length,browser:r.browserTargets.length,newContactsThisProcess:totalContacts}));}}));console.log('SCAN_FINISHED '+schools.length);}
if(process.argv[1]?.endsWith('/scan.mjs'))main().catch(e=>{console.error(e);process.exitCode=1;});
